[package]
name = "rust_test1"
version = "0.1.0"
authors = ["xx"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rc="0.1.1"

[profile.release]
lto = "fat"
codegen-units = 1
